# Generated by Django 4.1.7 on 2023-03-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclosion', '0003_cathegorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('affiche', models.ImageField(upload_to='')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclosion.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cathegorie',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Description1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Description2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Description3',
            new_name='description3',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Image2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Image3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Titre1',
            new_name='titre1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Titre2',
            new_name='titre2',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='Titre3',
            new_name='titre3',
        ),
        migrations.AddField(
            model_name='categorie',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclosion.project'),
        ),
    ]
