# Generated by Django 4.1.7 on 2023-03-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclosion', '0004_categorie_film_project_delete_cathegorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='timing',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
