# Generated by Django 4.1.7 on 2023-03-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclosion', '0006_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='categorie',
        ),
    ]
