# Generated by Django 4.1.7 on 2023-03-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclosion', '0007_rename_genre_film_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
