# Generated by Django 4.1.7 on 2023-03-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclosion', '0008_delete_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('affiche', models.ImageField(upload_to='')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclosion.categorie')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclosion.project')),
            ],
        ),
    ]
